Update commit-change.yml

diff --git a/.github/workflows/commit-change.yml b/.github/workflows/commit-change.yml
--- a/.github/workflows/commit-change.yml
+++ b/.github/workflows/commit-change.yml
@@ -49,18 +49,20 @@ jobs:
             fi
           done
 
-          echo "Packages: $(cat .packages)";
+          if [ -f .packages ]; then
+            echo "Packages: $(cat .packages)";
 
-          for package in $(cat .packages); do
-            if [ ! -z "${{ vars.IGNORE_LIST || env.IGNORE_LIST || secrets.IGNORE_LIST }}" ]; then
-              if [[ "${{ vars.IGNORE_LIST || env.IGNORE_LIST || secrets.IGNORE_LIST }}" =~ (^|[[:space:]])${package}($|[[:space:]]) ]]; then
-                continue
+            for package in $(cat .packages); do
+              if [ ! -z "${{ vars.IGNORE_LIST || env.IGNORE_LIST || secrets.IGNORE_LIST }}" ]; then
+                if [[ "${{ vars.IGNORE_LIST || env.IGNORE_LIST || secrets.IGNORE_LIST }}" =~ (^|[[:space:]])${package}($|[[:space:]]) ]]; then
+                  continue
+                fi
               fi
-            fi
-            npm install ${package} || echo "Failed: ${package}"
-          done;
+              npm install ${package} || echo "Failed: ${package}"
+            done;
 
-          rm .packages
+            rm .packages
+          fi
 
       - name: Reinstall dependencies
         run: npm ci
